fpdf/image_parsing.py
Ability to use bytesio buffer directly. This can simplify loading matplotlib plots into the PDF.
=> Proposing to add ability to use bytesio directly

fpdf/html.py, test/html_test.py
When positioning an image and align is set to center a new x position is calculated.
It might just be a bug but the current behaviour seems to be that it calculates the distance from the current x to the center of the page width remaining before taking the image width in to account. If the intent was to take the margins in to account then it's ignoring the right margin.
In order to center an image in the page the current value for x should be ignored which is what this change does.
=> Centering of html images incorrrectly offsets the x pos

fpdf/fpdf.py
in reference to [this issue](https://github.com/reingart/pyfpdf/pull/166) copied from [this PR](https://github.com/reingart/pyfpdf/pull/167)
=> fixed "User defined path to font is ignored"

MANIFEST.in, fpdf/fonts.py, fpdf/fpdf.py, fpdf/html.py, fpdf/image_parsing.py, fpdf/template.py, fpdf/util/__init__.py, fpdf/util/syntax.py, setup.py, test/end_to_end_legacy/charmap/charmap_test.py, tutorial/unicode.py
Remove some redundant code that is covered by defaults in Python 3.
And I had to include `README.md` to `MANIFEST.in`. Without that, `tox` failed with an error, that the file `'./README.md` could not be found. Wondering why nobody else had that problem.
=> Modernize code to Python 3.6+

CONTRIBUTORS.md, fpdf/fonts.py, fpdf/fpdf.py, fpdf/ttfonts.py, tutorial/tuto5.py
1. access dict.keys() implicitly
2. `range(0, x)` can be written as `range(x)`, simplify some loops and iterate directly over the elements
=> Compact some code

fpdf/fpdf.py, fpdf/util/syntax.py
Since Python 3.6, dictionaries are always insertion ordered. So there is no need anymore for `collection.OrderedDict()`.
This PR replaces `collection.OrderedDict()` with the standard `dict()`.
=> Replace collections.OrderedDict() with dict()

tox.ini
This allows running `tox -e py39 -- -x --ff -s` with the arguments for pytest
=> tox should send positional args to pytest

docs/Development.md, test/utilities.py
In #82 while converting the tests to pytest and making the `_qpdf` conversion in-memory only, I removed the `delete` argument from `assert_pdf_equal` because it wasn't relevant any more. With this PR all generated data will be stored in the `/tmp/pytest-of-$USER` directory structure and only older test runs will be deleted automatically.
I added an explanation to the docs as well.
=> Save all generated test files in /tmp/pytest-of-$USER

test/barcodes/test_barcodes.py, test/cells/test_cell.py, test/cells/test_multi_cell.py, test/class_unit_test/test_shape.py, test/end_to_end_legacy/charmap/test_charmap.py, test/fonts/test_fonts.py, test/html/test_html.py, test/image/image_types/test_insert_images.py, test/image/png_images/test_png_file.py, test/image/test_image_info.py, test/image/test_load_resource.py, test/image/test_url_images.py, test/template/test_template.py, test/test_alias.py, test/test_catalog.py, test/test_info.py, test/test_rotation.py, test/test_set_date.py, test/utilities.py, test/utils/test_load_cache.py
Use `pathlib.Path` for directory/files manipulation in the tests. Remove the `relative_path_to` method.
No change outside of the `test` directory.
=> Use pathlib.Path in tests

fpdf/fpdf.py, setup.py
This PR is independent from #86 as it adds `pathlib.Path` to the codebase and not to tests.
=> Use pathlib.Path in the code

fpdf/fpdf.py
Just a minor edit but improves compatibility to legacy pyfpdf code.
The previous definition was inconsistent with the documentation:
https://pyfpdf.github.io/fpdf2/reference/alias_nb_pages.html
which also led to the example not working.
`TypeError: alias_nb_pages() missing 1 required positional argument: 'alias'`
Using a default argument here can be a handy way to reset to default values.
=> add default argument to alias_nb_pages()

fpdf/deprecation.py, test/fonts/test_add_font.py
Fixed the call to super().__setattr__() causing an "expected 2 arguments, got 3" exception in Python 3.
=> Fix bug in deprecation.py

CONTRIBUTORS.md, test/conftest.py
The tests were failing on Windows because of a WindowsPath issue.
Making sure it is converted to a string fixes the problem.
=> Fix windows qpdf tests

test/conftest.py
Tests relying on this functionality will fail because the "expected" pdf will be generated without the date being handled.
Test to exercise this functionality is in the other pull request.
You can verify the code path is never used/tested currently by modifying your `.coveragerc` file with:
>     test/*.py
>     test/**/*.py
=> Fixed `assert_pdf_equal` not working when "expected" is an instance of FPDF

docs/Tutorial-es.md, docs/Tutorial-हिंदी.md, docs/Tutorial.md
I added the german version to both the spanish and hindi page which were missing it. I also added "version" next to "English" since that seemed to be the pattern
=> added links to other translations on Hindi and Spanish tutorial pages

docs/Tutorial-de.md, docs/Tutorial-es.md, docs/Tutorial-it.md, docs/Tutorial-pt.md, docs/Tutorial-हिंदी.md, docs/Tutorial.md
=> doc: add Portuguese tutorial 

fpdf/fpdf.py
Bad repeated render of whole "s" string instead of partial "txt_frag".
Signed-off-by: Martin Cerveny <m.cerveny@computer.org>
=> Fix: get_string_width() unicode and markdown broken

.pylintrc, CHANGELOG.md, fpdf/fpdf.py, tutorial/form.py, tutorial/tuto2.py, tutorial/tuto3.py, tutorial/tuto4.py, tutorial/tuto5.py
and also preserving backward compatibility with PyFPDF for passing positional arguments to `cell()` & `multi_cell()`, which was broken in 2.5.2 - fix #413
=> Fixing calls to FPDF.cell in tutorial/tuto*.py demo scripts to match new API since v2.5.2

docs/Templates.md
Tried running the example in the templates doc. The template example has invalid syntax (missing comma) and some of the options are invalid or misleading so I thought I fix them quickly : 
Changes: 
align: Option "I" doesn't exist, throws Error, changes to "C"
foreground/background: 0 means black, you cant use "None" so removing the option leads to the expected result
multiline: Needs to be boolean or None, not int, throws an error otherwise
No change in the codebase, docs only. Feel free to close if irrelevant. :)
=> Minor docs improvements: fixed template example

CHANGELOG.md, fpdf/drawing.py, fpdf/svg.py, test/svg/generated_pdf/use-xlink-href.pdf, test/svg/parameters.py, test/svg/svg_sources/use-xlink-href.svg
=> Fixing support for "x" & "y" attributes in SVG <use> tags

docs/index.md, docs/requirements.txt
https://github.com/PyFPDF/fpdf2/runs/7263726951?check_suite_focus=true
```
INFO     -  Output a PDF to "/home/runner/work/fpdf2/fpdf2/public/fpdf2-manual.pdf".
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.5/x64/bin/mkdocs", line 8, in <module>
sys.exit(cli())
File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-p …
```
=> Fix docs building

CHANGELOG.md, fpdf/svg.py, test/svg/parameters.py
e.g. Fixes #526
**Checklist**:
=> SVG stroke-width with explicit unit, fixes #526

CHANGELOG.md, fpdf/svg.py, test/svg/parameters.py
Provides a tiny fix to #555  
**Checklist**:
=> Use resolve_length in ShapeBuilder.rect

CHANGELOG.md, fpdf/fpdf.py, test/text/test_unbreakable.py
_cf._ https://github.com/PyFPDF/fpdf2/discussions/557
=> Forbid use of `get_y()` & `local_context()` inside `unbreakable()` as it is currently not supported

docs/LineBreaks.md
…lti_cell().  Some people have had difficulty determining if a multi_cell() would result in a line break prior to inserting the multi_cell() dating back to the old pyfpdf.
e.g. Fixes #0 
**Checklist**:
=> docs: LineBreaks.md.  multi_cell() page break clarification.

docs/Tutorial-es.md, docs/Tutorial.md
Update `Tutorial-es.md` to match the current version of the tutorial, using `Tutorial.md` as the reference (related issue #267). Before this update, the document only included tutorials 1 to 3 and the wording was slightly outdated.
I also added a missing word, fixed a minimal spelling mistake and added code formatting to a few variables in `Tutorial.md`.
**Checklist**:
=> Add tutorials 4 to 6 to `Tutorial-es.md`

fpdf/annotations.py, fpdf/fpdf.py, fpdf/output.py, test/image/test_load_image.py, test/image/test_oversized.py, test/test_perfs.py
Also provides a fix for the warning mentioned in #600
=> Fix: file attachment annotations should not be globally enclosed as /EmbeddedFiles, as they are already enclosed on the page they appear on

test/svg/test_transform_viewport.py
Increase test coverage for syg.py.  #395  This relates to the lines not covered in "transform_to_rect_viewport" function. 
**Checklist**:
=> Increase test coverage for svg.py

CHANGELOG.md, fpdf/image_parsing.py
Fixes #643 
Reduced the time required to add large images with the `FlateDecode` filter. Now adding an 8000x8000 RGB image takes only 1.3 seconds (was 55 seconds - see #643)
**Checklist**:
=> Fix performance issue with adding large images with `FlateDecode` image filter

CHANGELOG.md, fpdf/output.py, test/fonts/test_add_font.py, test/image/test_oversized.py
As discussed in #637, this is a first PR only to show a warning if the font is missing glyphs
e.g. Fixes #0 
**Checklist**:
=> Show warning if font is missing glyphs

CHANGELOG.md, README.md, docs/Tutorial-zh.md, docs/index.md, mkdocs.yml
From #267 
Added the Simplified Chinese tutorial page. The translation isn't perfect, but I've done my best. There is some adjustments in the order of words, but in all the gists are conveyed pretty well. 
=> Add Simplified Chinese tutorial

docs/Development.md, docs/Logging.md, fpdf/fpdf.py, test/outline/test_outline_html.py
=> Removing warning on HTML2FPDF_CLASS being deprecated

CHANGELOG.md, fpdf/actions.py, fpdf/annotations.py, fpdf/output.py, fpdf/prefs.py, fpdf/sign.py, fpdf/syntax.py, fpdf/transitions.py, test/encryption/encryption_with_hyperlink.pdf, test/encryption/test_encryption.py
=> fix encryption with hyperlink bug

CHANGELOG.md, fpdf/actions.py, fpdf/annotations.py, fpdf/encryption.py, fpdf/fpdf.py, fpdf/outline.py, fpdf/output.py, fpdf/syntax.py, fpdf/util.py, test/encryption/encrypt_outline.pdf, test/encryption/test_encryption.py
Fix https://github.com/PyFPDF/fpdf2/issues/732
Also introduces a new PDF object type: `PDFDate`
=> Fix outline encryption

CHANGELOG.md, docs/UsageInWebAPI.md
Added documentation on how to use FPDF using FastAPI and send the file via SMTP.
**Checklist**:
=> Added FastAPI documentation. Send PDF via SMTP

CHANGELOG.md, fpdf/fpdf.py, test/text/test_varied_fragments.py, test/text/varfrags_char_vpos.pdf
TextLines with Framents with alternating lift is not rendered correctly as lift operator is not reset. This is fixed here. 
**Checklist**:
=> Make sure 'lift' is reset if Fragment changes lift in _render_styled_text_line

.github/workflows/continuous-integration-workflow.yml, CHANGELOG.md, fpdf/html.py, scripts/checker_commons.py, scripts/pdfchecker.py, scripts/verapdf.py
With this refactoring, the pipeline step _"Checking all PDF samples"_ that uses to take ~12-14min to execute, would now take ~9min
=> Making CI pipeline faster by parallelizing the PDF checkers execution

CHANGELOG.md, fpdf/deprecation.py, fpdf/fpdf.py, fpdf/html.py, fpdf/recorder.py, fpdf/template.py, test/errors/test_FPDF_errors.py, test/fonts/test_add_font.py, test/fonts/test_set_font.py, test/html/test_html.py, test/shapes/test_polyline.py, test/test_output.py, test/text/test_cell.py, test/text/test_multi_cell.py, test/text/test_render_styled.py, test/text/test_unbreakable.py
Fix stacklevel of warnings such that warnings always point to the users code.
**Checklist**:
=> Fix stacklevel of warnings

tutorial/tuto5.py
cell_fill_logic is no longer an argument of Table
see https://py-pdf.github.io/fpdf2/fpdf/table.html#fpdf.table.Table
**Checklist**:
=> use cell_fill_mode

docs/History.md, docs/index.md, fpdf/fpdf.py, fpdf/html.py, fpdf/template.py, mkdocs.yml
Originally suggested by @gmischler there: https://github.com/py-pdf/fpdf2/discussions/433#discussioncomment-2853790
=> Documenting compatibility between PyFPDF & fpdf2

fpdf/fonts.py
Remove redundant calls to fonttools getBestCmap to improve performance on cases like the one reported on the issue #907 
**Checklist**:
=> Remove redundant calls to fonttools function

CHANGELOG.md, fpdf/__init__.py, fpdf/fpdf.py, test/text/test_markdown_parse.py
I also used this opportunity to improve the root module docstrings
=> Fixing edge case when parsing a Markdown link followed by a newline - fix #916

fpdf/fonts.py, fpdf/output.py, test/fonts/test_font_internals.py, test/text/test_cell.py
This is a follow-up to #911
I made minor performance-oriented improvements to `SubsetMap`:
* in 2 places, use a single call to `dict.get(key)` instead of `key in dict` + `dict[key]`
* define our own, fast, `__hash__()` method
* add a cache (`._char_id_per_unicode`) to avoid repeated processings in `SubsetMap.pick()`
I also used this opportunity to remove all accesses to the private property `._map`
from outside the `SubsetMap` class.
_cf._ https://github.com/py-pdf/fpdf2/issues/907 for some context
=> Draft: Making test_cell_speed_with_long_text() faster

docs/Tutorial-he.md
updated sections 4 and 5 of the hebrew tutorial, as requested in 
https://github.com/py-pdf/fpdf2/issues/267#issuecomment-1774813633
e.g. Fixes #0 
**Checklist**:
=> Hebrew tutorial translation section 4 and 5

fpdf/table.py
=> Adds tuple to 'text_align' docstring

fpdf/fpdf.py
Update the doc strings with additional information about interior cell margin c_margin. Add the additional description to `FPDF.cell()`, `FPDF.multi_cell()` and `FPDF.get_string_width()`.
This is result of the issue: https://github.com/py-pdf/fpdf2/issues/1009
=> Update doc strings for text width with c_margin info

docs/Tutorial-zh.md
Update translation for section 4&5 in simplified chinese tutorial as per requested in <a href="https://github.com/py-pdf/fpdf2/issues/267#issuecomment-1774813633">Comment on issue#267</a>
**Checklist**:
meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR. (N/A)
=> Update section 4&5 for simplified Chinese tutorial 

CHANGELOG.md, fpdf/fpdf.py, test/html/html_table_with_data_that_contains_entity_names.pdf, test/html/test_html_table.py
Fixes #1010 
False positive when attempting to detect nested html tags
Removes the unescape from write_html, data will be escaped when needed.
**Checklist**:
Had to remove the pre-commit hooks to commit as it was failing due to being on a Windows box and Python's chmod being very limited.
=> delay unescaping data so as not to confuse entity names as nested tags

.pre-commit-config.yaml, CHANGELOG.md
Updates the pre-commit version in .pre-commit-config.yaml from 1.5.1 -> 1.5.4
see comment in #1018 
**Checklist**:
=> Update pre-commit-hooks to version 1.5.4

CHANGELOG.md, fpdf/svg.py
This PR is a follow-up on a comment by @gmischler in https://github.com/py-pdf/fpdf2/pull/919#discussion_r1395515588
On second-thought, I think it's best to:
* not raise an error when parsing an unsupported SVG tag or attribute, in order to allow the end user to check the resulting PDF when those markup elements are just ignored
* report more clearly those unsupported SVG tags & attributes, as WARNING logs (and not just DEBUG ones as it used to be for unsupported tags). A good thing about WARNING logs is that they get displayed to _stderr_ with the default Python logging configuration (unlike DEBUG logs or calls to `warnings.warn()`)
=> Emitting warning logs for unsupported SVG tags & attributes

CHANGELOG.md, test/conftest.py
This is a follow-up on a comment by @gmischler in PR #1034
=> Tests: silencing fpdf.svg logs

.github/workflows/continuous-integration-workflow.yml, setup.cfg, tox.ini
Add python 3.12 on the CI
**Checklist**:
=> Support python 3.12

CHANGELOG.md, fpdf/__init__.py
=> Produce a warning when the installation of both pypdf & fpdf2 packages is detected

test/image/test_load_image.py
Fixes #1067
**Checklist**:
I don't think this change is meaningful enough to warrant addition to the contributors table
=> Make a test independent of test infrastructure speed

.github/workflows/continuous-integration-workflow.yml, scripts/install-pdfchecker.sh
=> New pdfchecker URL - Fix #1100

CHANGELOG.md, fpdf/drawing.py, fpdf/fpdf.py, fpdf/html.py, test/html/html_ul_bullet_color.pdf, test/html/test_html.py
Feature requested in https://github.com/py-pdf/fpdf2/discussions/1056
**Checklist**:
=> New ul_bullet_color parameter for FPDF.write_html()

CHANGELOG.md, fpdf/line_break.py
Fix a bug reported by @andrewlutz on #901
=> Fix bug ordering RTL runs on bidirectional text

scripts/changed_pdfs_comparison.html, scripts/compare-changed-pdfs.py
This utility script helps to check if reference PDF files in `test/` have been visually modified on the current branch, compared to the `master` branch.
=> Adding scripts/compare-changed-pdfs.py

fpdf/image_parsing.py, fpdf/text_region.py, test/text_shaping/test_bidirectional.py
=> fix new pylint alarms

fpdf/fpdf.py, fpdf/output.py, test/fonts/test_add_font.py, test/fonts/test_font_fallback.py
Implementing suggestion from https://github.com/py-pdf/fpdf2/issues/1171#issuecomment-2126845201.
Also slightly improving a docstring as mentioned there: https://github.com/py-pdf/fpdf2/issues/1156#issuecomment-2095444563
**Checklist**:
- [NA] A mention of the change is present in `CHANGELOG.md`
=> Including code points in warning for missing glyphs in fonts

CHANGELOG.md, fpdf/fpdf.py
**Changes:**
In `FPDF.add_font()`, a line of documentation about the accepted values of the `style` parameter is being clarified to explicitly mention the empty string case and infer that "BI" is an accepted value.
**Motives:**
I suspect this is the cause for a [misimplementation in typeshed's typing stubs](https://github.com/python/typeshed/blob/main/stubs/fpdf2/fpdf/fpdf.pyi#L70), which I have [opened a PR there](https://github.com/python/typeshed/pull/12677) to fix.
Sorry for this small PR, but I felt like it was appropriate. I'm looking forward to doing more (and bigger) docs clarifications if they're welcomed.
Thank you for working on this amazing project, maintainers!
**Checklist**:
meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the …
=> Clarify `FPDF.add_font()`'s `style` parameter accepted values

test/test_perfs.py
We seem to have hit the memory usage of 8MiB set on `test_intense_image_rendering()` for several weeks now:
It does not seem possible to me that this change of behaviour could be linked to a recent change in `fpdf2` code.
I noticed that this test failed when the CI pipeline switched from using **Python 3.12.5 to using 3.12.6**.
I could not find any mention of changes impacting memory in Python 3.12.6 release notes though:
https://www.python.org/downloads/release/python-3126/
Anyway, this PR increases the memory limit of this unit test from 8MiB to 15MiB.
**Checklist**:
=> [CI fixup] Extending test_intense_image_rendering() unit test test max memory usage

docs/Text.md, fpdf/fpdf.py
* adept comparison table in Text.md (add text shaping)
* add a note in the functions doc string
Fixes #1265 
**Checklist**:
=> Doc: mention that text() does lack features (#1265)

.github/workflows/continuous-integration-workflow.yml, README.md, docs/Development.md
Adopting https://github.com/anchore/grype vulnerability scanner
Current output from the CI pipeline execution:
```
Run anchore/scan-action@v3
/usr/bin/chmod +x /home/runner/work/_temp/0deb6c07-bb84-4737-9ac1-9e50389b3681
/home/runner/work/_temp/0deb6c07-bb84-4737-9ac1-9e50389b3681 -b /home/runner/work/_temp/0deb6c07-bb84-4737-9ac1-9e50389b3681_grype v0.74.4
[info] checking github for release tag='v0.74.4' 
[info] fetching release script for tag='v0.74.4' 
[info] checking github for release tag='v0.74.4' 
[info] using release tag='v0.74.4' version='0.74.4' os='linux' arch='amd64' 
[info] installed /home/runner/work/_temp/0deb6c07-bb84-4737-9ac1-9e50389b3681_grype/grype 
grype output...
Executing: grype -o sarif --fail-on medium dir:.
```
=> Adopting grype security scan

CHANGELOG.md, fpdf/html.py, test/html/html_table_with_null_text_in_span_cell.pdf, test/html/test_html_table.py
Fixes #1293
This Pr to fix HTML table with `td` tag have `rowspan`, `colspan` > 1 and text inside is null the pdf output not show table correctly
**Checklist**:
=> Fix the HTML table with null text in span cells that don't show correctly

scripts/install-verapdf.sh, scripts/verapdf.properties, test/test_perfs.py
* switch from VeraPDF v1.22.3 to v1.27.96
* add GPG signature verification on the VeraPDF ZIP archive downloaded
* increased the execution time threshold in `test_perfs.py` from 9s to 10s
=> Switching to VeraPDF 1.27.96

test/test_perfs.py
This test has been broken for a week:
I initially tried to solve this in PR https://github.com/py-pdf/fpdf2/pull/1318 by increasing the execution time threshold in `test_perfs.py` from 9s to 10s, but then this other error appeared:
```
FAILED test/test_perfs.py::test_intense_image_rendering - assert (291.9765625 - 267.390625) < 15
```
The annoying thing is that I do not quite understand why the RAM usage increased from 15MiB to 25MiB...
* last OK execution: https://github.com/py-pdf/fpdf2/actions/runs/11953462734/job/33321379801
* next KO execution: https://github.com/py-pdf/fpdf2/actions/runs/12074007599/job/33671208678
What differs?
Dependencies: `uharfbuzz` went from version `0.42.0` to `0.43.0`.
And the GitHub Actions runner image went from `20241117.1.0` to `20241124.1.0`
I tested …
=> Fixing test_intense_image_rendering() in CI pipeline

docs/index.md
Note: part of the changes originally embedded in this PR were moved to another dedicated PR: https://github.com/py-pdf/fpdf2/pull/1332
=> Doc: explaining how to verify provenance

CHANGELOG.md, fpdf/svg.py
- Optimized svg image rendering by avoiding deepcopy (uses copy=False flag when calling add_item in svg.build_group where item is known to be not re-used). This reduces time to render SVG's by 50%-70%.
**Checklist**:
=> Feature: SVG optimization

.github/workflows/continuous-integration-workflow.yml, CHANGELOG.md
Related doc: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-systems-like-github-actions
=> Fix mkdocs git-revision-date-localized plugin usage

docs/CombineWithMarkdown.md, fpdf/fpdf.py, test/text/multi_cell_markdown_strikethrough.pdf, test/text/test_markdown_parse.py, test/text/test_multi_cell_markdown.py
Follow-up of PR https://github.com/py-pdf/fpdf2/pull/1340
**Checklist**:
=> Support for ~~strikethrough~~ with markdown=True

.github/workflows/continuous-integration-workflow.yml, docs/Development.md, test/linters-requirements.txt
Now using [pinact](https://github.com/suzuki-shunsuke/pinact) to pin versions of Actions and Reusable Workflows,
and [zizmor](https://woodruffw.github.io/zizmor/) to perform static analysis on our pipeline definition files.
=> Introducing Github Actions linter zizmor

docs/index.md
Not documenting `pypi-attributions` for now, as recommended by @woodruffw: https://github.com/trailofbits/pypi-attestations/issues/85#issuecomment-2779481313
=> Doc: removing paragraph regarding pypi-attestations

.github/workflows/continuous-integration-workflow.yml
The workflow is failing because pykcs11 (endesive dependency) is failing on windows python 3.13.3+
This change will freeze the python 3.13.3 version for windows on the workflow.
**Checklist**:
=> Actions: Force python 3.13.3 for windows on the test matrix

CHANGELOG.md, fpdf/line_break.py, test/text/test_line_break.py
An instance of `SubstitutionFragment` is also an instance of `Fragment`. With certain orderings, a substitution fragment could be extended with characters from another fragment. When the substitution fragment is later replaced with a value, all of those characters are lost.
For example, before the fix, the string `f'There are {{nb}} pages'` was rendered as `There are 20`.
Two consecutive substitution fragments will still be merged. Since there is only one substitution fragment, you'll see one value in the result file.
**Checklist**:
=> Prevent merging fragments of different types.
