fpdf/image_parsing.py
from urllib.request import urlopen
=> added import urlopen for correct working

docs/reference/header.md
Copied from https://github.com/reingart/pyfpdf/pull/172
Thanks @JonathanCollaud!
=> Docs: fixing typo in header.md

CHANGELOG.md, fpdf/fpdf.py, setup.py
todo publish 2.2.0 but if this is okay then i can publish 2.2.0rc1 right away
=> Changelog pep 440 and version change

README.md, docs/Metadata.md, fpdf/fpdf.py, mkdocs.yml
Preview with Github Markdown renderer: https://github.com/PyFPDF/fpdf2/blob/add-docs-metadata/docs/Metadata.md
Merging this PR will allow to close https://github.com/PyFPDF/fpdf2/issues/51
=> Adding docs page on how to add metadata - close #51

fpdf/errors.py, fpdf/fpdf.py, fpdf/html.py, fpdf/image_parsing.py, fpdf/template.py, fpdf/ttfonts.py, fpdf/util/__init__.py, fpdf/util/syntax.py, setup.py, test/catalog_test.py, test/end_to_end_legacy/charmap/charmap_test.py, test/html/test_html.py, test/image/png_images/png_file_test.py, tutorial/set_metadata.py, tutorial/tuto2.py, tutorial/tuto3.py, tutorial/tuto4.py, tutorial/unicode.py
Now this is a draft of continuation of #68, so it includes all its commits and I will rebase it when the other one gets merged.
*It works on my computer™*, but I want to check it with GHA CI before I leave it for a review.
=> Replace sprintf, %, and .format with f-strings 

README.md
_cf._ https://pypi.org/project/fpdf2/
=> Using an absolute URL in README.md so that it gets properly rendered in Pypi

fpdf/fonts.py, fpdf/fpdf.py, fpdf/image_parsing.py, fpdf/template.py, fpdf/util/syntax.py, test/fonts/test_set_font.py, test/html/test_html.py
A few independent code compactings.
=> Some code compactings

.github/workflows/continuous-integration-workflow.yml, CHANGELOG.md, README.md, docs/Images.md, docs/Links.md, docs/index.md, fpdf/fpdf.py, mkdocs.yml, test/image/test_url_images.py, test/simple_text_annotation.pdf, test/test_text_annotations.py
This PR also adds a documlentation page on images.
Currently it includes commits from https://github.com/PyFPDF/fpdf2/pull/130,
so it should be rebased & merged after it.
=> Implementing text annotations - close #60

CODEOWNERS
I dont have the time to actually do much work for this project consistently anymore and would like to set expectations more reasonably
=> do not send notifications to alexp

README.md, docs/Tutorial-de.md, docs/Tutorial-es.md, docs/Tutorial-it.md, docs/Tutorial-हिंदी.md, docs/Tutorial.md
Translating is not my main job but my mother tongue is Italian and I speak English every day. 
I also went around all the files to fix/add the link to the new italian translation
=> add italian translation for Tutorial doc

docs/Tutorial-de.md, docs/Tutorial-es.md, docs/Tutorial-fr.md, docs/Tutorial-it.md, docs/Tutorial-pt.md, docs/Tutorial-ru.md, docs/Tutorial-हिंदी.md, docs/Tutorial.md
I've updated the links to tutorials in other languages.
=> doc: updated links in tutorial

CHANGELOG.md, fpdf/fpdf.py
=> Switch from UTF-16BE encoding to utf-16-be

fpdf/fpdf.py
Fixes #331 
**Checklist**:
Congrats for this awesome project, works great in AWS Lambda function to generate reports in PDF, very lightweight and with few dependencies, low memory requirements.
This is my first PR in GitHub, so I hope to be doing it right 😌
=> Log substitute_page_number function at DEBUG level

fpdf/errors.py, fpdf/fpdf.py, test/errors/test_FPDF_errors.py
=> Fix Issue #330

fpdf/errors.py, test/errors/test_FPDF_errors.py, test/metadata/test_display_mode.py
e.g. Small test improvements to increase the coverage on errors.py and fpdf.py.
**Checklist**:
I can see in the coverage report that there are a few places where we could add new tests or improve the existing ones to increase the coverage. Do you think I am going in the right direction here in terms of the changes?
Also I am not sure if it's worth changing the CHANGELOG.md file for this change.
=> Test improvements to increase coverage

test/utils/test_byte_conversion.py, test/utils/test_escape_parens.py
Increase test coverage on utils.py - #395 
**Checklist**:
I thought it would be a good idea to add some extra test coverage on utils.py, since tests act as documentation as well. It could be a bit redundant, but I'm happy to make changes!
=> Utils test

CHANGELOG.md, README.md, docs/index.md, fpdf/svg.py, setup.py, test/svg/parameters.py
_cf._ #450
This is pending https://github.com/regebro/svg.path/pull/88 & https://github.com/regebro/svg.path/issues/89 before it could be merged
=> Using svg.path to parse SVG files

docs/Development.md
=> Fix broken link

test/errors/test_FPDF_errors.py, test/fonts/test_add_font.py, test/shapes/test_polyline.py
Those have gone on my nerves long enough... 🙄 
=> fix warnings in tests

README.md, docs/UsageInWebAPI.md, docs/index.md, tutorial/README.md, tutorial/notebook.ipynb
Preview: https://github.com/PyFPDF/fpdf2/blob/jupyter/tutorial/notebook.ipynb
(the top buttons/links do not work a they purposely point to the `master` branch)
Remains to do: add links to it in the documentation
=> Jupyter notebook

CHANGELOG.md, fpdf/fpdf.py, test/image/test_load_image.py, test/text/cell_lasth.pdf, test/text/test_cell.py
e.g. Fixes #601 
**Checklist**:
=> fix zero height ln() after empty cell(), #601

CHANGELOG.md, docs/TemplatingWithJinja.md, docs/requirements.txt, mkdocs.yml
Preview: https://github.com/PyFPDF/fpdf2/blob/jinja/docs/TemplatingWithJinja.md
=> Adding docs on using jinja & fpdf2

CHANGELOG.md, fpdf/__init__.py, fpdf/deprecation.py, fpdf/fpdf.py, test/errors/test_FPDF_errors.py
=> Improving error message if fpdf module is instantiated

.github/workflows/continuous-integration-workflow.yml
Helps investigation made in https://github.com/PyFPDF/fpdf2/issues/641
=> Draft: debugging memory usage

CHANGELOG.md, fpdf/enums.py, fpdf/fonts.py, fpdf/html.py, fpdf/outline.py, fpdf/structure_tree.py, fpdf/svg.py, fpdf/syntax.py, fpdf/table.py, test/svg/parameters.py
Also fixes git merge artifacts remaining in `enums.py`, _cf._ https://github.com/PyFPDF/fpdf2/issues/743
=> Supporting percent width/height in <rect> + adding some __slots__ to reduce RAM usage

tutorial/notebook.ipynb
=> Translate out of place french comment in docs, very minor fix

docs/Text.md
**Checklist**:
Bringing more of the docs up to date with the new text shaping miracle.
=> Update Text.md wrt. text shaping

docs/TextShaping.md, fpdf/fpdf.py
Fix 2 small typos in documentation and in a comment introduced in #820. 
**Checklist**:
=> fix typos in doc/comment

docs/Development.md
Fixes a typo.
**Checklist**:
meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR. N/A
=> DOC: PyPDF → fpdf2

CHANGELOG.md, docs/CombineWithLivereload.md, mkdocs.yml, tutorial/watch_with_livereload.py
Final documentation page URL when this will be merged:
[Combine with livereload](https://py-pdf.github.io/fpdf2/CombineWithLivereload.html)
=> Adding docs/CombineWithLivereload.md

test/text/test_cell.py
=> Bumping time threshold of test_cell_speed_with_long_text() from 20s to 22s

docs/Tutorial-bn.md, docs/Tutorial-de.md, docs/Tutorial-es.md, docs/Tutorial-fr.md, docs/Tutorial-gr.md, docs/Tutorial-he.md, docs/Tutorial-hi.md, docs/Tutorial-it.md, docs/Tutorial-ja.md, docs/Tutorial-km.md, docs/Tutorial-pt.md, docs/Tutorial-ru.md, docs/Tutorial-zh.md, docs/Unicode.md
**Checklist**:
- [NA] A unit test is covering the code added / modified by this PR
- [NA] A mention of the change is present in `CHANGELOG.md`
=> Tutorial updates, tuto4 and tuto5 retranslations required

docs/Tutorial-es.md
Update sections 4 and 5 of the Spanish tutorial as requested in https://github.com/py-pdf/fpdf2/issues/267#issuecomment-1774813633
**Checklist**:
=> Update sections 4 and 5 of the Spanish tutorial

setup.cfg
...while waiting for a proper fix in PR #1022
_cf._ explanation in issue https://github.com/py-pdf/fpdf2/issues/1021
=> Quick & dirty fix so that our tests pass, by setting a max version for fonttools

CHANGELOG.md, docs/Development.md, docs/overrides/main.html, fpdf/fpdf.py
**Checklist**:
- [NA] A unit test is covering the code added / modified by this PR
=> Release 2.7.7

CHANGELOG.md, docs/CombineWithMistletoeoToUseMarkdown.md, fpdf/svg.py, mkdocs.yml, tutorial/markdown2pdf.py
Preview of the new documentation page:
=> Add some documentation on how to combine with mistletoe - close #1103

.github/workflows/continuous-integration-workflow.yml
GitHub Actions documentation:
* https://github.com/marketplace/actions/pypi-publish
* https://github.com/marketplace/actions/gh-action-sigstore-python
The workflow execution was tested in this run: https://github.com/py-pdf/fpdf2/actions/runs/7732708584/job/21083215501?pr=1105
=> [CI/GA] Using pypa/gh-action-pypi-publish & sigstore/gh-action-sigstore-python

CHANGELOG.md, docs/overrides/main.html, fpdf/fpdf.py
=> release v2.7.8

CHANGELOG.md, fpdf/outline.py
e.g. Fixes #1112  
**Checklist**:
=> Fix type hint for outline section level member

CHANGELOG.md, docs/overrides/main.html, fpdf/fpdf.py
=> release 2.7.9

CHANGELOG.md, fpdf/fpdf.py, test/html/html_customize_ul.pdf, test/html/test_html.py
=> Fixing #1198

CHANGELOG.md, fpdf/drawing.py, test/drawing/parameters.py
Convert hex strings to uppercase to support case insensitive hex colors.
Fixes #1225  
**Checklist**:
=> Support lowercase hex values

docs/PageBreaks.md, docs/TextShaping.md, docs/index.md, docs/overrides/main.html
**Checklist**:
- [NA] A unit test is covering the code added / modified by this PR
- [NA] A mention of the change is present in `CHANGELOG.md`
=> Adding warning in documentation for issue #1090

CHANGELOG.md, docs/UsageInWebAPI.md
**Checklist**:
- [NA] A unit test is covering the code added / modified by this PR
=> Docs on using fpdf2 with gunicorn

docs/Presentations.md
Fixes a typo in docs.
**Checklist**:
=> Fix Typo in Presentations.md

CHANGELOG.md, README.md, docs/index.md, setup.cfg, tox.ini
Close https://github.com/py-pdf/fpdf2/issues/1296
=> Officially dropping support for Python 3.7

.pylintrc, CHANGELOG.md, docs/Development.md, docs/Metadata.md, fpdf/enums.py, fpdf/fpdf.py, fpdf/prefs.py
=> Adding optional title parameter to text_annotation()

.github/workflows/continuous-integration-workflow.yml, setup.cfg
=> CI: installing the minimal versions of the dependencies in the test pipeline, to ensure that they remain compatible

docs/DocumentOutlineAndTableOfContents.md, fpdf/fpdf.py
=> FPDF: Document pdf.page, warn against modifying manually

.github/workflows/continuous-integration-workflow.yml, fpdf/drawing.py
=> Fix CI pipeline by using runner ubuntu-22.04 - cf. #1333

docs/EmojisSymbolsDingbats.md, mkdocs.yml
=> Doc: adding warning about color emojis

docs/Development.md, docs/Shapes.md, docs/index.md
=> Doc: minor fixups

.github/workflows/continuous-integration-workflow.yml, docs/Development.md, docs/requirements.txt, mkdocs.yml
=> Doc: adding privacy & git-revision-date-localized plugins

docs/Tutorial-de.md, docs/Tutorial.md
Fixed some typos in Tutorial.md and Tutorial-de.md 
**Checklist**:
=> fix: some typos

.github/workflows/continuous-integration-workflow.yml, scripts/install-verapdf.sh, test/pdf-a/README.md
=> CI: restoring VeraPDF check

CHANGELOG.md, docs/Metadata.md, docs/Tutorial-de.md, docs/Tutorial.md, fpdf/fpdf.py, fpdf/output.py, test/output_intents/test_output_intents.py, test/pdf-a/README.md, test/pdf-a/test_pdf_a.py, tutorial/tuto7.py
=> Minor edits to the PDF/A tutorial

CHANGELOG.md, fpdf/fpdf.py, test/test_positioning.py
This original method did not allow substituting 0 (zero as a number) into the method, however, I had a case where it needed to be done .ln(0) - that is, with 0 indentation in height. I added the None check (if h is not None):. This way the methods will be more intuitive, I spent almost an hour trying to figure out why I still had this stupid indentation.
e.g. Fixes #0 
**Checklist**:
=> Fixxed ln() method  FPDF class

.github/workflows/continuous-integration-workflow.yml, CHANGELOG.md, fpdf/svg.py
=> SVG: minor regular-expression optim

.github/workflows/continuous-integration-workflow.yml, contributors/package-lock.json, contributors/package.json, docs/Development.md, renovate.json
=> Renovate fine-tunning

docs/overrides/main.html
=> Doc: added mention to banner

.github/workflows/continuous-integration-workflow.yml, docs/CombineWithBorb.md, docs/Development.md, docs/EmojisSymbolsDingbats.md, docs/Templates.md, docs/Tutorial-bn.md, docs/Tutorial-de.md, docs/Tutorial-es.md, docs/Tutorial-fr.md, docs/Tutorial-gr.md, docs/Tutorial-he.md, docs/Tutorial-hi.md, docs/Tutorial-id.md, docs/Tutorial-it.md, docs/Tutorial-ja.md, docs/Tutorial-km.md, docs/Tutorial-nl.md, docs/Tutorial-pl.md, docs/Tutorial-pt.md, docs/Tutorial-ru.md, docs/Tutorial-sl.md, docs/Tutorial-tr.md, docs/Tutorial-zh.md, docs/Tutorial.md, docs/plugins/check_toc.py, mkdocs.yml, setup.cfg
I reported the problem there: https://github.com/squidfunk/mkdocs-material/discussions/8252
=> Docs: fix Templates ToC & add plugin check_toc

CHANGELOG.md, docs/Maths.md
What changes are being made?
Added documentation on integrating fpdf2 with the Ibis library for rendering Ibis DataFrames as tables in PDF documents.
Provided best-practice installation instructions and a step-by-step example using Ibis with DuckDB and fpdf2.
Clarified code comments and updated the relevant section in the docs for accuracy.
Mentioned the documentation addition in CHANGELOG.md for traceability.
e.g. Fixes #1477 
**Checklist**:
N/A (Documentation-only change)
N/A (Not a new feature; documentation update)
=> Added appropriate documentation for the Ibis Library

docs/Tutorial-es.md
Translate tutorial 7 into Spanish.
**Checklist**:
=> Add Tutorial 7 to Tutorial-es.md

fpdf/html.py, fpdf/image_parsing.py, fpdf/svg.py, fpdf/table.py, fpdf/template.py, fpdf/util.py, test/signing/README.md
=> Doc: fix docstrings in fpdf.template

.github/workflows/continuous-integration-workflow.yml, CHANGELOG.md, README.md, docs/index.md, setup.cfg, test/pdf-a/test_pdf_a.py, test/signing/test_sign.py, tox.ini
=> Drop python 3.8 support

test/image/test_oversized.py
=> Increase memory threshold

docs/UsageInWebAPI.md
=> doc: add example fpdf2 usage with bottle web framework
